apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.app}}-env-configmap
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.envMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}


