{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-form-ingestion
  namespace: {{ .Release.Namespace }}
spec:
  serviceAccountName: prometheus-form-ingestion
  podMonitorSelector:
    matchLabels:
      prometheus: {{ .Release.Namespace }}
  serviceMonitorSelector:
    matchLabels:
      prometheus: {{ .Release.Namespace }}
  resources:
    requests:
      memory: 400Mi
{{- end }}