apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- toYaml .Values.service.labels | nindent 4 }}
spec:
  ports:
  - name: {{ .Values.service.portName }}
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.portProtocol }}
    targetPort: {{ .Values.service.targetPort}}
  selector:
    {{- include "form.applabel" . |nindent 4 }}
    {{- include "form.selectorLabels" . | nindent 4 }}
    {{- toYaml .Values.pod.labels | nindent 4 }}
  type: {{ .Values.service.type }}

