apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
    - mesh
    - {{ .Values.istioGateway.name }}
  hosts:
    - {{ .Values.istioGateway.host }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.virtualService.prefix }}
      route:
        - destination:
            host: {{ .Values.virtualService.destination }}
            port:
              number: {{ .Values.virtualService.port }}
